package part1;
import java.util.function.Function;

/**
 * Generated by MATLAB2Java
*/
public abstract class Integrator {
	Function<Double, Double> f;
	double lowerBound;
	double upperBound;
	double stepSize;
	int[] distribution;
	int stepSizeModifier;
	String methodName;
	public Integrator(Function<Double, Double> f, double lowerBound, double upperBound, double stepSize,
			int[] distribution, int stepSizeModifier, String methodName) {
		this.f = f;
		this.lowerBound = lowerBound;
		this.upperBound = upperBound;
		this.stepSize = stepSize;
		this.distribution = distribution;
		this.stepSizeModifier = stepSizeModifier;
		this.methodName = methodName;
	}
	
	public void integrate() {
		double returnValue = 0;
		for (double x_i = lowerBound; x_i < upperBound; x_i += stepSize) {
			returnValue += integrateOneStep(x_i);
		}
		
		System.out.printf("	%s returned: %.4f" + System.lineSeparator(), methodName, returnValue);
	}

	abstract double integrateOneStep(double x_i);
	
	public boolean wantArea() {
		return false;
	}
}
